# please copy this file to your project directory
version: '3'
services:
  serverless:
    build: 
      context: .
      args: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    # keep container up (docker run -t)
    tty: true
    working_dir: /app
    volumes:
      - ..:/app
    image: serverless
    container_name: serverless
    env_file:
      - .env
