# 1. copy this file in your project root
# 3. change the image and container_name
version: '3'
services:
  serverless:
    build: 
      context: .
      args: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    # keep container up (docker run -t)
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    # please change from selerless to serverless-<YOUR_PROJECT_NAME>
    image: serverless
    # please change from selerless to serverless-<YOUR_PROJECT_NAME>
    container_name: serverless
    env_file:
      - .env
