# 1. copy this file in your project root
# 2. change dockerfile, image, and container_name
version: '3'
services:
  serverless:
    build: 
      context: .
      # change from "." to "./sls/Dockerfile"
      dockerfile: .
      args: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    # keep container up (docker run -t)
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    # change from "selerless" to "serverless-<YOUR_PROJECT_NAME>"
    image: serverless
    # change from "selerless" to "serverless-<YOUR_PROJECT_NAME>"
    container_name: serverless
    env_file:
      - .env
