version: '3.5'
services:
  serverless:
    build: 
      context: .
      args: 
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    # keep container up (docker run -t)
    tty: true
    # attach STDIN of container (docker run -i)
    stdin_open: true
    image: serverless
    container_name: serverless
    env_file:
      - .env
